Attendance/urls.py
from django.urls import path
from .views import index, pcs_detail,  pcs_add, list_pcs

app_name = 'Attendance'
urlpatterns = [
    path('', index, name='home page'),
    path('pcs/', list_pcs, name='list_pcs'),
    path('pcs/<slug:slug>', pcs_detail, name='pcadetails'),
    # path('new_pcs/', create_pcs_name, name='add_new_pcs'),
    # path('pcsadd/', create_pcs_name, name='new_pcs'),
    path('addpc/', pcs_add, name='add_pcs'),
    ]

PCMember/urls.py
from django.urls import path
from PCMember.views import  member_list, member_detail, Import_csv, member_add

app_name = 'PCMember'
urlpatterns = [
    path('list_member/', member_list, name='listmemeber'),
    path('list_member/<slug:slug>', member_detail, name='member_details'),
    # path('add_member/', create_pcmember, name='new_member'),
    path('import_csv_member/', Import_csv, name="Import_csv"),
    path('add_member/', member_add, name='member_new'),

]

PC_attend/urls.py
from django.urls import path

from PC_attend import views
from PC_attend.views import *

app_name = 'PC_attend'

urlpatterns = [
    path('Alist/', attendance_list, name='attendance_list'),
    path('Alist/<id>', detail_view_attendance, name='details_attend'),
    path('Acreate/', attendance_add, name='new_attend'),
    path('ajax/load_member', load_members, name='ajax_load_member'),

]

accounts/urls.py
from django.urls import path
from accounts.views import login_user, register_user

app_name = 'accounts'

urlpatterns = [
    path('login/', login_user, name='user_login'),
    path('signup/', register_user, name='user_sign_up'),

]

djangoProject7/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('hello/', admin.site.urls),
    path('', include('Attendance.urls')),
    # path('jets/',include('jets.urls','jet')),
    path('members/', include('PCMember.urls')),
    path('attends/', include('PC_attend.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{{ section.title }}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'dist/img/ctaclogo.png' %}">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet"
          href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/dropzone/min/dropzone.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
</head>
<body class="hold-transition sidebar-mini sidebar-collapse  layout-navbar-fixed ">
<div class="wrapper">

    <div class="preloader flex-column justify-content-center align-items-center">
        <img class="animation__shake" src="{% static 'dist/img/ctaclogo.png' %}" alt="CtacLogo" height="60" width="60">
    </div>


    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'Attendance:home page' %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>


            </ul>

            <form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search"
                           aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>


        </nav>

        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="{% url 'Attendance:home page' %}" class="brand-link">
                <img src="{% static 'dist/img/ctaclogo.png' %}" alt="CTACLogo"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">CTAC</span>
            </a>
            <div class="sidebar">
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <li class="nav-item has-treeview ">
                            <a href="#" class="nav-link">
                                <i class="fas fa-layer-group"></i>
                                <p>
                                    PCA NAMES
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{% url 'Attendance:list_pcs' %}" class="nav-link">
                                        <p>List</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'Attendance:add_pcs' %}" class="nav-link">
                                        <p>Add New Name</p>
                                    </a>
                                </li>

                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="fas fa-pen-nib"></i>
                                <p>
                                    ATTENDANCE
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">

                                <li class="nav-item">
                                    <a href="{% url 'PC_attend:attendance_list' %}" class="nav-link">
                                        <p>Attendance list</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'PC_attend:new_attend' %}" class="nav-link">

                                        <p>Create Attendance</p>
                                    </a>
                                </li>

                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="fas fa-users"></i>
                                <p>
                                    PC MEMBER
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{% url 'PCMember:listmemeber' %}" class="nav-link">

                                        <p>Members</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'PCMember:member_new' %}" class="nav-link">
                                        <p>Add New</p>
                                    </a>
                                </li>

                            </ul>
                        </li>


                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    ACCOUNTS
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">

                            </ul>
                        </li>
                    </ul>
                    </li>
                </nav>
            </div>
        </aside>

        {% block content %}

        {% endblock %}
        <footer class="main-footer">
            {#            added a tag to get current year of the footer #}
            <strong>Copyright 2014 - {% now "Y" %} &copy;</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Fiifi Ahwireng </b>
            </div>
        </footer>
        <aside class="control-sidebar control-sidebar-dark">
        </aside>
    </div>

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
    <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <script src="{% static 'dist/js/adminlte.js' %}"></script>
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/dropzone/min/dropzone.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>


    </body>
</div>
</body>
</html>

templates/create_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/detailsattendance.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ data.pcs_name }} |{{ data.service_date }} {% endblock %}
{% block content %}
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        {#                        <h1>{{ mem_det.pc_member_last_name|lower|capfirst  }} &nbsp;{{ mem_det.pc_member_first_name }} {{ mem_det.pc_member_othername }}</h1>#}
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            {#                            <li class="breadcrumb-item"><a href="{% url 'Attendance:home page' %}">Home</a></li>#}
                            {#                            <li class="breadcrumb-item"><a href="{% url 'PCMember:listmemeber' %}">Members</a></li>#}
                            {#                            <li class="breadcrumb-item active">{{ mem_det.pc_member_last_name }}</li>#}
                        </ol>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
                        <div class="row">
                            <div class="col-12 col-sm-4">
                                <div class="info-box bg-light">
                                    <div class="info-box-content">
                                        <span class="info-box-text text-center text-muted"> Service Date</span>
                                        <span class="info-box-number text-center text-muted mb-0">{{ data.service_date|date:"M d, Y" }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="info-box bg-light">
                                    <div class="info-box-content">
                                        <span class="info-box-text text-center text-muted"> Group Name </span>
                                        <span class="info-box-number text-center text-muted mb-0">{{ data.pcs_name }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{{ data.pcs_name|lower|capfirst }}

                    </div>
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Last Name</th>

                            </tr>
                            </thead>
                            <tbody>

                            <tr>
                                {% for pc_member in data.pc_member.all %}
                                    <p>{{ pc_member }}&nbsp; </p>
                                    <p></p>

                                {% endfor %}

                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/detailsmember.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | {{ mem_det.pc_member_last_name }} {% endblock %}
{% block content %}
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ mem_det.pc_member_last_name|lower|capfirst  }} &nbsp;{{ mem_det.pc_member_first_name }} {{ mem_det.pc_member_othername }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'Attendance:home page' %}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'PCMember:listmemeber' %}">Members</a></li>
                            <li class="breadcrumb-item active">{{ mem_det.pc_member_last_name }}</li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
                        <div class="row">
                            <div class="col-12 col-sm-4">
                                <div class="info-box bg-light">
                                    <div class="info-box-content">
                                        <span class="info-box-text text-center text-muted"> Group Head</span>
                                        <span class="info-box-number text-center text-muted mb-0">{{ mem_det.pcs_head.first_name }}&nbsp;{{ mem_det.pcs_head.last_name}}</span>
                                    </div>
                                </div>
                            </div>
                             <div class="col-12 col-sm-4">
                                <div class="info-box bg-light">
                                    <div class="info-box-content">
                                        <span class="info-box-text text-center text-muted"> Group Name </span>
                                       <span class="info-box-number text-center text-muted mb-0">{{ mem_det.pcs_name }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{{ mem_det.pc_member_last_name|lower|capfirst }} &nbsp; {{ mem_det.pc_member_first_name|lower|capfirst }}</h3>
                    </div>
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Last Name</th>
                                <th>First Name</th>
                                <th>Other Name</th>
                                <th>Phone Number</th>
                                <th>Whatsapp Number</th>
                                <th>GPS Address</th>
                                <th>House Address</th>

                            </tr>
                            </thead>
                            <tbody>
{#                            {% for mem_det in mem_det %}#}
                                <tr>
                                    <td>{{ mem_det.id }}</td>
                                    <td>{{ mem_det.pc_member_last_name |lower|capfirst }}</td>
                                    <td>{{ mem_det.pc_member_first_name|lower|capfirst}}</td>
                                    <td>{{ mem_det.pc_member_othername|lower|capfirst }}</td>
                                    <td>{{ mem_det.pc_member_phone }}</td>
                                   <td>{{ mem_det.whats_phone }}</td>
                                   <td>{{ mem_det.pc_member_gps_address }}</td>
                                   <td>{{ mem_det.pc_member_house_address }}</td>

                                </tr>
{#                            {% endfor %}#}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/listattendance.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | List Attendance {% endblock %}
{% block content %}

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>PCS Attendance</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'Attendance:home page' %}">Home</a></li>
                            <li class="breadcrumb-item active">Attendance</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>


        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Pastoral Care Attendance</h3>
                            </div>
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>PCS NAME</th>
                                        <th>SERVICE DATE</th>
                                        <th>PRESENT</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for attlist in attlist %}
                                        <tr>
                                            <td>{{ attlist.id }}</td>
                                            <td>
                                                <a href="{% url 'PC_attend:details_attend' attlist.id %}">{{ attlist.pcs_name }}</a>
                                            </td>
                                            <td>{{ attlist.service_date | date:'M d, Y' }} </td>
                                            <td>{{ attlist.present }}</td>

                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </section>
    </div>


{% endblock %}

templates/listmember.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | Members {% endblock %}
{% block content %}

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>PCS MEMBERS</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'Attendance:home page' %}">Home</a></li>
                            <li class="breadcrumb-item active">Members</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>


        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Pastoral Care Members</h3>
                            </div>
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>PCS NAME</th>
                                        <th>MEMBER LAST NAME</th>
                                        <th>MEMBER FIRST NAME</th>
                                        <th>MEMBER PHONE NUMBER</th>
                                        <th>MEMBER CHAPEL</th>
                                        <th>GROUP HEAD</th>
                                        <th>DATE ADDED</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for memelist in memelist %}
                                        <tr>
                                            <td>{{ memelist.id }}</td>
                                            <td> {{ memelist.pcs_name }}</td>
                                            <td><a href="{% url 'PCMember:member_details' memelist.slug %}"
                                            class ="link-black text-md">{{ memelist.pc_member_last_name }}</a></td>
                                            <td>{{ memelist.pc_member_first_name }}</td>
                                            <td>{{ memelist.pc_member_phone }}</td>
                                            <td>{{ memelist.chapel }}</td>
                                            <td>{{ memelist.pcs_head.last_name |lower|capfirst  }}&nbsp;{{ memelist.pcs_head.first_name |lower|capfirst  }}</td>
                                            <td>{{ memelist.created_at | date:'M d, Y' }}</td>


                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </section>
    </div>


{% endblock %}

templates/listpcs.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | List PCS {% endblock %}
{% block content %}

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>PCS CARE GROUPS</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'Attendance:home page' %}">Home</a></li>
                            <li class="breadcrumb-item active">Care Groups</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>


        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Pastoral Care Groups</h3>
                            </div>
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>PCS NAME</th>
                                        <th>DATE ADDED</th>
                                        <th>PCS HEAD</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for pcslt in pcslt %}
                                        <tr>
                                            <td>{{ pcslt.id }}</td>
                                            <td><a href="{% url 'Attendance:pcadetails' pcslt.slug %}"
                                                   class="link-black text-md"> {{ pcslt.pcs_name }}</a></td>
                                            <td>{{ pcslt.created_at | date:'M d, Y' }}</td>
                                            <td>{{ pcslt.user.last_name |lower|capfirst }}&nbsp;{{ pcslt.user.first_name |lower|capfirst }}</td>


                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </section>
    </div>


{% endblock %}

templates/newattend.html
<form method = "post"  id ="attendanceForm" data-member-url ='{% url 'PC_attend:ajax_load_member' %}'>
    {% csrf_token %}
    {{new_atts.as_p }}
    <input type="submit" value=Submit">
</form>

<script src = "https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("id_pcsname").change(function (){
        var url =$("#attendanceForm").attr("data-member-url");
        var pcsId =$(this).val();
        $.ajax({
            url:url,
            data:{
                'pcs_name' : pcsId
            },
            success:function (data) {
                $("#id_member").html(data);
            }
        })
    })

</script>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dancing</title>
</head>
<body>
{% block content %}

    {% csrf_token %}
    {{ form }}

{% endblock %}



</body>
</html>